version: '3.8'

services:
  frontend:
    image: vue-frontend
    build:
      context: ./movie-rating
    ports:
      - "5173:80" # Map host port 5173 to container port 80
    depends_on:
      backend:
        condition: service_healthy

  backend:
    image: spring-backend
    build:
      context: ./backend/movie-rating
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/mydb
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/movie-rating
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mongo-data: