spring:
  data:
    mongodb:
      uri: mongodb+srv://mrrkhann9:cIMeR4eH3ZiNWqaF@cluster0.wxwcu.mongodb.net/movie-rating?retryWrites=true&w=majority&appName=Cluster0
# TMDB API Configuration
tmdb:
  api:
    key: b5ae5122817663a88047316d6a837481
    base-url: https://api.themoviedb.org/3

# Server Configuration
server:
  port: 8080

